# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name ksreflect_C
#'
#' @title Kernel-type estimator based on the reflection method (C++ version)
#'
#' @param r Distance
#' @param data Pseudo data
#' @param h Bandwidth
#' @param kernel Type of kernel: epan, gaussian, or uniform
#' @param shape Shape of estimator: general or monotone
#'
#' @return Numeric value of the estimator
ksreflect_C <- function(r, data, h, kernel, shape) {
    .Call(`_NPcov_ksreflect_C`, r, data, h, kernel, shape)
}

#' @name eval_sse_C
#'
#' @title Computing SSE of an estimator obtained by the IDEA algorithm (C++ version)
#'
#' @param storage Data storage
#' @param x Input (e.g., distance)
#' @param y Output (e.g., correlation value)
#' @param h Bandwidth
#' @param kernel Type of kernel: epan, gaussian, or uniform
#' @param shape Shape of estimator: general or monotone
#'
#' @return SSE
eval_sse_C <- function(storage, x, y, h, kernel, shape) {
    .Call(`_NPcov_eval_sse_C`, storage, x, y, h, kernel, shape)
}

#' @name evalEach_sse_C
#'
#' @title Computing SSE of an estimator obtained by the IDEA algorithm for each pseudo data (C++ version)
#'
#' @param data Pseudo data
#' @param x Input (e.g., distance)
#' @param y Output (e.g., correlation value)
#' @param h Bandwidth
#' @param kernel Type of kernel: epan, gaussian, or uniform
#' @param shape Shape of estimator: general or monotone
#'
#' @return SSE
evalEach_sse_C <- function(data, x, y, h, kernel, shape) {
    .Call(`_NPcov_evalEach_sse_C`, data, x, y, h, kernel, shape)
}

